# Generated by Django 4.2.3 on 2025-04-12 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_by',
            field=models.ManyToManyField(null=True, related_name='selected_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
