# Generated by Django 5.2 on 2025-04-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizscore',
            old_name='score',
            new_name='points',
        ),
    ]
