# Generated by Django 5.2 on 2025-04-16 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_score_quizscore_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='selected_by',
            field=models.ManyToManyField(blank=True, related_name='selected_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
