# Generated by Django 4.2.3 on 2025-04-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_answer_selected_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='total',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
