# Generated by Django 4.2.3 on 2025-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_quizscore_total_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
