# Generated by Django 5.2 on 2025-04-24 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='points',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
