# Generated by Django 5.2 on 2025-04-30 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_question_points_alter_quiz_total_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='quiz.category'),
        ),
    ]
